name       : mate-dock-applet
version    : 21.10.0
release    : 24
source     :
    - https://github.com/ubuntu-mate/mate-dock-applet/archive/refs/tags/21.10.0.tar.gz : 42f06dcac13aae19a9bbd16272854c896044aa0301a69319cab86ef4ffd8b09c
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : An application dock applet for the MATE panel
description: |
    An application dock applet for the MATE panel
rundeps    :
    - bamf
    - libnotify
    - mate-panel
    - pyxdg
    - python3-cairo
    - python-gobject
    - python-pillow
    - python-xlib
setup      : |
    %reconfigure --with-gtk3
build      : |
    %make
install    : |
    %make_install
