name       : mate-dock-applet
version    : '0.77'
release    : 3
source     :
    - https://github.com/robint99/mate-dock-applet/archive/V0.77.tar.gz : 7e6871be54f9d2d4b53bb5e9f6c63219dcbbfbd28e337d6bec4dc5adb03122b8
license    : GPL-3.0
component  : desktop.mate
summary    : An application dock applet for the MATE panel
description: |
    An application dock applet for the MATE panel
rundeps    :
    - keybinder
    - mate-panel
    - pyxdg
    - python3-cairo
    - python-pillow
    - python-gobject
setup      : |
    %reconfigure --with-gtk3
build      : |
    %make
install    : |
    %make_install
