name       : mate-dock-applet
version    : 0.86
release    : 10
source     :
    - https://github.com/robint99/mate-dock-applet/archive/V0.86.tar.gz : 2546e03800d69ab05491b12bc5631c9c05eb96e1892e72ffb36f613b2b00bc98
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : An application dock applet for the MATE panel
description: |
    An application dock applet for the MATE panel
rundeps    :
    - bamf
    - libnotify
    - mate-panel
    - pyxdg
    - python3-cairo
    - python-pillow
    - python3-gobject
    - python-xlib
setup      : |
    %reconfigure --with-gtk3
build      : |
    %make
install    : |
    %make_install
