name       : mate-dock-applet
version    : 0.87
release    : 11
source     :
    - https://github.com/robint99/mate-dock-applet/archive/V0.87.tar.gz : 69b8b3dc5fb9d9e4c2e2e18a7a7d5ef9daed796f3c6003ddb389e4209b29d404
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : An application dock applet for the MATE panel
description: |
    An application dock applet for the MATE panel
rundeps    :
    - bamf
    - libnotify
    - mate-panel
    - pyxdg
    - python3-cairo
    - python-pillow
    - python3-gobject
    - python-xlib
setup      : |
    %reconfigure --with-gtk3
build      : |
    %make
install    : |
    %make_install
