name       : mate-dock-applet
version    : 0.73
release    : 1
source     :
    - https://github.com/robint99/mate-dock-applet/archive/V0.73.tar.gz : fd6151ffea0dc8d688dc736cd84d6cc27f8cf6e1669bb6afb7e9f0461f867a4b
license    : GPL-3.0
component  : desktop.mate
summary    : An application dock applet for the MATE panel
description: |
    An application dock applet for the MATE panel
rundeps    :
    - mate-panel
    - pyxdg
    - python3-cairo
    - python-pillow
    - python-gobject
setup      : |
    %reconfigure --with-gtk3
build      : |
    %make
install    : |
    %make_install
