name       : mate-dock-applet
version    : 19.10.0
release    : 16
source     :
    - https://github.com/ubuntu-mate/mate-dock-applet/archive/19.10.0.tar.gz : 4536f39e58cb7195dc59fc821696a6b3701617d962e99fa622e51626548a71c0
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : An application dock applet for the MATE panel
description: |
    An application dock applet for the MATE panel
rundeps    :
    - bamf
    - libnotify
    - mate-panel
    - pyxdg
    - python3-cairo
    - python-pillow
    - python3-gobject
    - python-xlib
setup      : |
    %reconfigure --with-gtk3
build      : |
    %make
install    : |
    %make_install
